### ISSUE TITLE
Change source.type type

### ISSUE THREAD

**Issue by alexanderkirtzel** [elbwalker/walkerOS#194]
**Is your feature request related to a problem? Please describe.**
The event's source.type should be a string instead of an enum.
```ts
interface Source {
  type: SourceType; // <-- should be string
}
```

**Describe the solution you'd like**
Change `Source.type` from being a SourceType enum to a simple string
The walker will use `web` as the default value.

**Comment by wintercodeNKJJ** [comment]
Hi pleas could take on this issue?

**Comment by alexanderkirtzel** [comment]
You're welcome, @wintercodeNKJJ 
Since the changes are breaking, it would go live with v1.5
But it's a good push to make the move. Reach out if you need help :)

**Comment by wintercodeNKJJ** [comment]
Should I do the same change in the following file
`dist > src > types > elbwalker.dts`
