### ISSUE TITLE
Walker.js for Node.js

### ISSUE THREAD

**Issue by danlin604** [elbwalker/walkerOS#250]
**Is your feature request related to a problem? Please describe.**
We have have some serverside analytics that needs to be send to OpenSearch following Walker.js's format. Is there a way to run walker.js in a node environment or to keep its payload format consistent between browser and server.

One approach seems to be mimicking walker's general format:
```JavaScript
    // Expected object
    // {
    //     event: 'page view',
    //     data: { domain: 'localhost', title: 'Webiny', referrer: '', id: '/' },
    //     context: {},
    //     globals: {},
    //     user: {},
    //     nested: [],
    //     consent: {},
    //     id: '1683666821051-vvdx8f-1',
    //     trigger: 'load',
    //     entity: 'page',
    //     action: 'view',
    //     timestamp: 1683666821052,
    //     timing: 51.86,
    //     group: 'vvdx8f',
    //     count: 1,
    //     version: { config: 0, walker: 1.6 },
    //     source: { type: 1, id: 'http://localhost:3000/', previous_id: '' }
    //   }

    await sendToKinesis({
        event: "email view",
        data: { domain: "email", title: action, referrer: "", id: "/" },
        context: {},
        globals: {
            browser: headers["sec-ch-ua"],
            os: headers["sec-ch-ua-platform"],
            device_type: headers["sec-ch-ua-mobile"],
            userAgent: headers["user-agent"],
            acceptLanguage: headers["accept-language"],
            ip: headers["x-forwarded-for"]
        },
        user: queryData.user,
        nested: [],
        consent: {},
        id: `${Date.now()}-${Math.floor(Math.random() * 2000)}`,
        trigger: "load",
        entity: "email",
        action: "view",
        timestamp: Date.now(),
        version: { config: 0, pixel: 1.0 },
        source: { type: 1, id: request?.headers["x-native-host"], previous_id: "" }
    });
```

Another approach is to use some sort of polyfill and run walker.js in node.js and send analytics via `elb()`.

**Describe the solution you'd like**
Please advice on server side usage and solutions.

**Describe alternatives you've considered**
- Build a custom JS Object
- Use a polyfill to run walker.js in node.js
- Use puppeteer

**Additional context**

**Comment by alexanderkirtzel** [comment]
This is very interesting.
What about a server-side package without the browser-related stuff, fully controllable via `elb` calls?
Would you expect destinations to work the same way?

**Comment by danlin604** [comment]
That will work I think.

The idea is so that the format of the analytics will mirror the browser side analytics.

Assuming we receive a JSON analytics payload, calling elb and targeting a destination we will end up with a very similar analytics payload.
